apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argcdtestdeploy
  name: argcdtestdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argcdtestdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argcdtestdeploy
    spec:
      containers:
      - image: nginx:1.23.1
        name: nginx
        resources: {}
status: {}
