apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: csvserver
  name: csvserver
spec:
  ports:
  - name: myport
    port: 80
    protocol: TCP
    targetPort: 9300
  selector:
    app: csvserver
  type: ClusterIP
status:
  loadBalancer: {}
